<?php echo $this->partial('index/add.phtml', array(
    'formData' => $this->formData,
    'domains' => $this->domains,
    'error' => isset($this->error) ? $this->error : null,
    'domainContext' => isset($this->domainContext) ? $this->domainContext : false,
    'domainId' => isset($this->domainId) ? $this->domainId : null,
    'domainName' => isset($this->domainName) ? $this->domainName : null,
)); ?>
